language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - x.sotomayor@alumnos.upm.es
script:
- mvn verify
  mvn sonar:sonar \
  -Dsonar.projectKey=b2lero_IWVG.SwC.XavierSotomayor \
  -Dsonar.organization=b2lero-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=$SONAR